name: App Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.repository == 'jellyfin/jellyfin-android' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Set dev JELLYFIN_VERISON
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "JELLYFIN_VERSION=$(echo ${VERSION#v} | tr / -)-dev" >> $GITHUB_ENV

      - name: Build Unsigned Release
        run: ./gradlew --no-daemon --info assembleRelease versionTxt

      - name: Split APK release types
        run: |
          mkdir -p build/jellyfin-publish/release-libre build/jellyfin-publish/release-proprietary;
          mv app/build/outputs/apk/*/*/jellyfin-android-*-libre-release-unsigned.apk build/jellyfin-publish/release-libre/;
          mv app/build/outputs/apk/*/*/jellyfin-android-*-proprietary-release-unsigned.apk build/jellyfin-publish/release-proprietary/;
          mv app/build/version.txt build/jellyfin-publish/;

      - uses: actions/upload-artifact@v2
        with:
          name: build-publish-artifact
          retention-days: 30
          if-no-files-found: error
          path: build/jellyfin-publish
